### ISSUE TITLE
Improvements for UX when logged

### ISSUE THREAD

**Issue by Marfullsen** [sebarocks/mcswitch#2]
### Tengo un par de ideas a nivel de experiencia de usuario que podría ayudar bastante.

- Al encender el server, una pantalla con las letras "Running" con fondo blanco, así ayudaría a intuir que el servidor está encendido, además de un botón rojo que permita apagar el servidor.

![server_sorrego_server_on](https://user-images.githubusercontent.com/56993209/170871695-f6a299be-c902-4c65-b5c8-8a85037db1d5.png)

---

- Por otro lado, al estar el servidor apagado, se visualizarían las letras "Stopped" con fondo negro. Para hacer más intuitivo el botón de encendido debiera ser verde.

![server_sorrego_server_off](https://user-images.githubusercontent.com/56993209/170871697-9a96536e-42b6-49bc-b9ff-484d4c3f5678.png)

---

En ambos casos se incluye una especie de insignia que permite al usuario logueado visualizar su nombre junto a una imágen predeterminada, sugiero que estén disponibles por defecto imágenes de mobs y personajes del juego.

Con eso termino mis sugerencias.
¡Mucho éxito!
:)

**Comment by sebarocks** [comment]
Cambios fueron implementados e incorporados a rama master
